### ISSUE TITLE
Can't change iOS STRIP_STYLE from FF UI

### ISSUE THREAD

**Issue by wonderu** [FlutterFlow/flutterflow-issues#5850]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I try to use tflite_flutter_plugin, during the start of the code it generates the error:
> Failed to lookup symbol 'TfLiteModelCreateFromFile': dlsym (RTLD_DEFAULT, TfLiteModelCreateFromFile): symbol not found

Problem could be solved only by adding `STRIP_STYLE = "non-global";` in `ios/Runner.xcodeproj
/project.pbxproj` file.

### Expected Behavior

I'm able to use set `STRIP_STYLE = "non-global";` without changing iOS project files in Platforms -> Advanced iOS Settings.

### Steps to Reproduce

1. Try to execute model using tflite_flutter_plugin in iOS
2. It generates the error:
> Failed to lookup symbol 'TfLiteModelCreateFromFile': dlsym (RTLD_DEFAULT, TfLiteModelCreateFromFile): symbol not found

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/HluIVgosda1c/qdcFqhQMkQzM6bZI7ku1EdwEhfa6uP7AMdczCQFBLYtenYEFYIlCJnkkG0d79kdrLL/E4KUmaRYQ+1oRXQQrjcHGnM6abEbWwWnMmMNNXfW6l5rWF2hF7ANNsSkIs2WeYefCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

n/a

### Environment

```markdown
- FlutterFlow version: 5.5.2
- Platform: iOS
- Browser name and version: n/a
- Operating system and version affected: 18.4
```

**Comment by Alezanello** [comment]
Hello!

In this case, one possible solution would be to push your code to GitHub and set up a GitHub Action that automatically updates the necessary files whenever FlutterFlow pushes changes. This way, you can avoid making those updates manually each time.

After that, you can use FlutterFlow’s *Deploy from GitHub* feature to deploy your project:<br>[https://docs.flutterflow.io/deployment/deploy-from-github/](https://docs.flutterflow.io/deployment/deploy-from-github/)

This approach allows you to apply the custom changes needed for your code to work as expected.<br>At the moment, this is the only available workaround for this scenario.

**Comment by wonderu** [comment]
@Alezanello thanks. I've implemented it.

```
# .github/workflows/update-version.yml
name: Auto Update Version

on:
  push:

jobs:
  update-version:
    if: github.actor != 'github-actions' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Update version in pubspec.yaml
        run: |
          # Read current version
          current_version=$(grep "version:" pubspec.yaml | sed 's/version: //')
          # Extract version number (without build number)
          version_number=$(echo $current_version | cut -d'+' -f1)
          # Use GitHub Actions run number + 130 as build number
          new_build_number=$(( ${{ github.run_number }} + 130 ))
          # Update pubspec.yaml
          sed -i "s/version: $current_version/version: $version_number+$new_build_number/" pubspec.yaml

      - name: Update project.pbxproj
        run: |
          # Add STRIP_STYLE before each ASSETCATALOG_COMPILER_APPICON_NAME
          sed -i 's/ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;/STRIP_STYLE = "non-global";\n\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Commit and push changes
        run: |
          git add pubspec.yaml ios/Runner.xcodeproj/project.pbxproj
          git commit -m "Auto-update version build number to $(( ${{ github.run_number }} + 130 )) and add STRIP_STYLE" || echo "No changes to commit"
          git push

```
